[project]
name = "interval-calculator"
version = "1.0.0"
description = "Interval Analyzer & Plotter"
requires-python = ">=3.9"
dependencies = [
    "flet",
    "sympy",
    "matplotlib",
]

[tool.flet]
product = "Interval Calculator"
org = "com.proo0"
bundle_id = "com.proo0.intervalcalculator"
build_number = 4

[tool.flet.android]
extract_packages = ["matplotlib"]
